pluginManagement {
    repositories {
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url 'https://repo1.maven.org/maven2/' }
        maven { url 'https://maven.dremio.com/free/' }
        gradlePluginPortal()
    }
}

rootProject.name = 'whoodle'
include 'whoodle-core'
include 'whoodle-testdata'
include 'whoodle-avro'
